# Generated by Django 5.2.8 on 2025-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="matricula",
            field=models.CharField(unique=True),
        ),
    ]
