# Generated by Django 5.2.8 on 2025-11-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do equipamento (ex: Capacete, Luva de Raspa)",
                        max_length=100,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("CABECA", "Proteção da Cabeça"),
                            ("OLHOS", "Proteção Ocular/Facial"),
                            ("AUDITIVA", "Proteção Auditiva"),
                            ("RESPIRATORIA", "Proteção Respiratória"),
                            ("TRONCO", "Proteção do Tronco"),
                            ("MEMBROS_SUP", "Proteção Membros Superiores (Mãos)"),
                            ("MEMBROS_INF", "Proteção Membros Inferiores (Pés)"),
                            ("CORPO_INTEIRO", "Proteção Corpo Inteiro"),
                            ("OUTRO", "Outro"),
                        ],
                        default="OUTRO",
                        max_length=20,
                    ),
                ),
                (
                    "ca",
                    models.CharField(
                        blank=True,
                        help_text="Número do C.A. do equipamento (se aplicável)",
                        max_length=20,
                        null=True,
                        verbose_name="Certificado de Aprovação (C.A.)",
                    ),
                ),
                (
                    "estoque_total",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade total deste item comprada pela empresa.",
                    ),
                ),
                (
                    "estoque_disponivel",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade disponível no estoque para empréstimo.",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_ultima_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
        ),
    ]
