# Generated by Django 5.2.8 on 2025-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="estoque_total",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Quantidade total deste item comprada pela empresa.",
            ),
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="nome",
            field=models.CharField(
                help_text="Nome do equipamento (ex: Capacete, Luva de Raspa)",
                max_length=100,
                unique=True,
            ),
        ),
    ]
