# Generated by Django 6.0.2 on 2026-02-27 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colaboradores", "0001_initial"),
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_emprestimo",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Empréstimo"
                    ),
                ),
                (
                    "data_prevista_devolucao",
                    models.DateField(verbose_name="Data Prevista para Devolução"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("DEVOLVIDO", "Devolvido"),
                            ("ATRASADO", "Atrasado"),
                        ],
                        default="ATIVO",
                        max_length=20,
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emprestimos",
                        to="colaboradores.colaborador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemEmprestado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_emprestada", models.PositiveIntegerField(default=1)),
                (
                    "status_item",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONCLUIDO", "Concluído"),
                            ("FORNECIDO", "Fornecido (Entrega Definitiva)"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status do Item",
                    ),
                ),
                (
                    "emprestimo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_emprestados",
                        to="emprestimos.emprestimo",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emprestimos_itens",
                        to="equipamentos.equipamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoDevolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_devolvida", models.PositiveIntegerField()),
                ("data_devolucao", models.DateTimeField(auto_now_add=True)),
                (
                    "status_devolucao",
                    models.CharField(
                        choices=[
                            ("DEVOLVIDO", "Devolvido"),
                            ("DANIFICADO", "Danificado"),
                            ("PERDIDO", "Perdido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "item_emprestado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_devolucoes",
                        to="emprestimos.itememprestado",
                    ),
                ),
            ],
        ),
    ]
