# Generated by Django 5.2.8 on 2025-11-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colaboradores", "0002_alter_colaborador_matricula"),
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_emprestimo",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Empréstimo"
                    ),
                ),
                (
                    "data_prevista_devolucao",
                    models.DateField(verbose_name="Data Prevista para Devolução"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("DEVOLVIDO", "Devolvido"),
                            ("ATRASADO", "Atrasado"),
                        ],
                        default="ATIVO",
                        max_length=20,
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emprestimos",
                        to="colaboradores.colaborador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemEmprestado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "status_item",
                    models.CharField(
                        choices=[
                            ("EM_USO", "Em Uso"),
                            ("DEVOLVIDO", "Devolvido"),
                            ("DANIFICADO", "Danificado"),
                            ("PERDIDO", "Perdido"),
                        ],
                        default="EM_USO",
                        max_length=20,
                        verbose_name="Status do Item",
                    ),
                ),
                (
                    "data_devolucao_item",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Devolução do Item"
                    ),
                ),
                (
                    "emprestimo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_emprestados",
                        to="emprestimos.emprestimo",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emprestimos_itens",
                        to="equipamentos.equipamento",
                    ),
                ),
            ],
        ),
    ]
