# Generated by Django 5.2.8 on 2025-11-16 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprestimos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itememprestado",
            old_name="quantidade",
            new_name="quantidade_emprestada",
        ),
        migrations.RemoveField(
            model_name="itememprestado",
            name="data_devolucao_item",
        ),
        migrations.AlterField(
            model_name="itememprestado",
            name="status_item",
            field=models.CharField(
                choices=[("PENDENTE", "Pendente"), ("CONCLUIDO", "Concluído")],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status do Item",
            ),
        ),
        migrations.CreateModel(
            name="HistoricoDevolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_devolvida", models.PositiveIntegerField()),
                ("data_devolucao", models.DateTimeField(auto_now_add=True)),
                (
                    "status_devolucao",
                    models.CharField(
                        choices=[
                            ("DEVOLVIDO", "Devolvido"),
                            ("DANIFICADO", "Danificado"),
                            ("PERDIDO", "Perdido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "item_emprestado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_devolucoes",
                        to="emprestimos.itememprestado",
                    ),
                ),
            ],
        ),
    ]
