# Generated by Django 5.2.8 on 2025-11-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "emprestimos",
            "0002_rename_quantidade_itememprestado_quantidade_emprestada_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itememprestado",
            name="status_item",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("CONCLUIDO", "Concluído"),
                    ("FORNECIDO", "Fornecido (Entrega Definitiva)"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status do Item",
            ),
        ),
    ]
